services:
  cv_builder:
    build:
      context: ./cvbuilder
      dockerfile: Dockerfile
    container_name: cv_builder
    env_file:
      - ./cvbuilder/.env
    volumes:
      - ./cvbuilder:/app
    working_dir: /app
    stdin_open: true
    tty: true