version: "3.9"

services:
  cv_builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv_builder
    env_file:
      - ./cvbuilder/.env
    volumes:
      - ./cvbuilder:/app
    working_dir: /app
    command: python main.py
